---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  comment = NA, 
               # echo = FALSE, 
               warning = FALSE, 
               message = FALSE, 
               error = TRUE, 
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# bcv

<!-- badges: start -->
<!-- badges: end -->

## Install

Install the `bcv` package from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("databrew/bcv")
```

## Example

Here is how to use it.

### Populate a credentials file

Create a `credentials.yaml` file with the following parameters:

```
dbname: 
host: 
user: 
pass:
port: 
traccar_url: 
traccar_user: 
traccar_pass: 
```

### Run code

```{r}
library(bcv)
library(yaml)

# Read in credentials
credentials <- yaml::yaml.load_file('../credentials/credentials.yaml')

# Syncronize between the worker registrationd data (collected via the shiny app)
# and the traccar server app
sync_workers(credentials = credentials)

# Get list of registered workers on the server which syncs with the
# shiny registration app
workers <- bcv::get_registered_workers(dbname = credentials$dbname,
                                       host = credentials$host,
                                       user = credentials$user,
                                       pass = credentials$pass)

# Or, get data for just one specified worker
worker1 <- get_registered_workers(unique_id = 1,
                                       dbname = credentials$dbname,
                                       host = credentials$host,
                                       user = credentials$user,
                                       pass = credentials$pass)

# Get list of workers whose info has been passed to the traccar server
traccar <- bcv::get_traccar_data(url = credentials$traccar_url,
                                 user = credentials$traccar_user,
                                 pass = credentials$traccar_pass)

# Get list of registered cases
cases <- get_cases(dbname = credentials$dbname,
                   host = credentials$host,
                   user = credentials$user,
                   pass = credentials$pass)

# Get case details of just 1 id
case1 <- get_cases(unique_id = 1,
                   dbname = credentials$dbname,
                   host = credentials$host,
                   user = credentials$user,
                   pass = credentials$pass)

# Get locations for one person based on their worker ID
location_history <- get_positions_from_unique_id(url = credentials$traccar_url,
                             user = credentials$traccar_user,
                             pass = credentials$traccar_pass,
                             unique_id = 1)

# Get reports using a unique id to fetch device id: possible reports - trips, summary, stops, route, events

# by trips - each row is a single "trip" with start and stop lat/lon for a given unique id
reports_trips <- get_reports_from_unique_id(url = credentials$traccar_url,
                             user = credentials$traccar_user,
                             pass = credentials$traccar_pass,
                             report_type = 'trips',
                             unique_id = 1)

# by stops - each row is a reported stop with details on position and time idle. the positionId column can be linked to the startPositionId and endPositionId in "trips"
reports_stops <- get_reports_from_unique_id(url = credentials$traccar_url,
                             user = credentials$traccar_user,
                             pass = credentials$traccar_pass,
                             report_type = 'stops',
                             unique_id = 1)

# by events - each row is an event : deviceOnline, deviceMoving, deviceStopped, or deviceUnknown
reports_events <- get_reports_from_unique_id(url = credentials$traccar_url,
                             user = credentials$traccar_user,
                             pass = credentials$traccar_pass,
                             report_type = 'events',
                             unique_id = 1)

# by route - each row is a position (lat/lon) with a time stamp. the id column can be linked 'id' column in "events"
reports_route <- get_reports_from_unique_id(url = credentials$traccar_url,
                             user = credentials$traccar_user,
                             pass = credentials$traccar_pass,
                             report_type = 'route',
                             unique_id = 1)



# by summary - returns one row per unique id with a summary of all movents (avg speed, distance, device name, etc)
reports_summary <- get_reports_from_unique_id(url = credentials$traccar_url,
                             user = credentials$traccar_user,
                             pass = credentials$traccar_pass,
                             report_type = 'summary',
                             unique_id = 1)

```

```{r, eval = FALSE}
# Generate a report for a worker who tests positive
# Note: for this function, supply path to credentials, rather than a credentials list
generate_report(unique_id = 1,
                credentials_file = '../credentials/credentials.yaml',
                output_dir = '~/Desktop',
                output_file = 'example_report.html')
```

# How to update the shiny app

```
sudo su - -c "R -e \"remove.packages('bcv')\"" ; sudo su - -c "R -e \"devtools::install_github('databrew/bcv', dependencies = TRUE, force = TRUE)\""; sudo systemctl restart shiny-server
```

